### ISSUE TITLE
[BUG] Disabling the plugin causes an error

### ISSUE THREAD

**Issue by pjeby** [vslinko/obsidian-zoom#62]
**Describe the bug**
Disabling the plugin results in the following error, and a notification that the plugin could not be disabled:

```
Plugin failure: obsidian-zoom RangeError: Field is not present in this state
    at e.field (app.js:1:349660)
    at KeepOnlyZoomedContentVisible.calculateHiddenContentRanges (eval at <anonymous> (app.js:1:1490278), <anonymous>:759:38)
    at ZoomFeature.calculateHiddenContentRanges (eval at <anonymous> (app.js:1:1490278), <anonymous>:818:50)
    at Array.DetectRangeBeforeVisibleRangeChanged.detectVisibleContentBoundariesViolation (eval at <anonymous> (app.js:1:1490278), <anonymous>:110:68)
    at app.js:1:347742
    at Lr (app.js:1:347900)
    at e.update (app.js:1:349809)
    at e.dispatch (app.js:1:485144)
    at e.updateOptions (app.js:1:1275115)
    at t.updateOptions (app.js:1:1606405)
```

**To Reproduce**
1. In the sandbox vault, turn off safe mode and install the plugin
2. Enable the plugin
3. Disable the plugin

**Expected behavior**
Plugin should disable without error.

**Desktop (please complete the following information):**
 - OS: Windows
 - Obsidian Version: 0.14.5
 - Plugin Version: 0.2.8

**Comment by MSBack** [comment]
I reproduced this issue.

**Comment by vslinko** [comment]
It seems to have been fixed in some version.
